sudo: required
dist: precise
language: node_js
node_js:
    - "12"
    - "14"
    - "16"
script: npm test
notifications:
    email:
        recipients:
            - vios.job@gmail.com
        on_success: change
        on_failure: always
